color normal    white default
color attachment brightyellow default
color hdrdefault cyan default
color indicator brightwhite default
color markers   brightred default
color quoted    green default
color signature cyan default
color tilde     blue default
color tree      red default
color quoted1 green default
